name: clean_relases
on:
 workflow_dispatch:


jobs:
  cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: clean relases and tags
        run: |
         chmod +x ./.github/clean_relases.sh
         ./.github/clean_relases.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: clean workflow_runs
        run: |
          gh api repos/${{ github.repository }}/actions/runs \
          --paginate -q '.workflow_runs[] | select(.head_branch == "master") | "\(.id)"' | \
          xargs -n1 -I % gh api repos/${{ github.repository }}/actions/runs/% -X DELETE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}